### ISSUE TITLE
Error 2 when play mkv file

### ISSUE THREAD

**Issue by dsleon** [simonjhogan/PLAYz-Media-for-PLEX#62]
When i try to reproduce some MKV files (high res, multi channel audio) i receive a error 2 in the app.

My tv is a LG 55LA7400 and The PMS server is installed on a MAC Mini.

I set all the debugging flags on the server and it returned this messages:

Oct 05, 2014 17:48:00 [0x108f7e000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:00 [0x108f7e000] DEBUG - Request: [192.168.1.210:55204] GET /library/metadata/15273?X-Plex-Access-Time=1412549277985 (26 live)
Oct 05, 2014 17:48:00 [0x108f7e000] DEBUG -  \* X-Plex-Access-Time => 1412549277985
Oct 05, 2014 17:48:00 [0x108f7e000] DEBUG - Selected a foreign audio track.
Oct 05, 2014 17:48:00 [0x108f7e000] DEBUG - It took 0.000874 sec to serialize a list with 1 elements.
Oct 05, 2014 17:48:00 [0x108f7e000] VERBOSE - Completed request: GET /library/metadata/15273: 2200
Oct 05, 2014 17:48:00 [0x10bc47000] VERBOSE - Finished writing response for GET /library/metadata/15273, 0 bytes in 91ms
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG - Request: [192.168.1.210:55205] GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655&X-Plex-Access-Key=BWSV622WQARJQHWA1KNQ&X-Plex-Access-Time=1412549280&X-Plex-Access-Code=iiA6%2BLrTjvbaTt2oI2NK%2FH4VBta2ZRGukxu9lZDOYT8%3D (28 live)
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG -  \* quality => 10
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG -  \* 3g => 0
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG -  \* url => http://192.168.1.38:32400/library/parts/15655
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG -  \* X-Plex-Access-Key => BWSV622WQARJQHWA1KNQ
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG -  \* X-Plex-Access-Time => 1412549280
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG -  \* X-Plex-Access-Code => iiA6+LrTjvbaTt2oI2NK/H4VBta2ZRGukxu9lZDOYT8=
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG - Cookie header in secure request: 
Oct 05, 2014 17:48:01 [0x10ebd5000] DEBUG - Checking cookie ''
Oct 05, 2014 17:48:01 [0x10ebd5000] ERROR - Client 'BWSV622WQARJQHWA1KNQ' access code is incorrect.
Oct 05, 2014 17:48:01 [0x10ebd5000] VERBOSE - Completed request: GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655: 401
Oct 05, 2014 17:48:02 [0x1089f4000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:02 [0x1089f4000] DEBUG - Request: [192.168.1.210:55207] GET /:/progress?key=15273&identifier=com.plexapp.plugins.library&time=0&state=playing (29 live)
Oct 05, 2014 17:48:02 [0x1089f4000] DEBUG -  \* key => 15273
Oct 05, 2014 17:48:02 [0x1089f4000] DEBUG -  \* identifier => com.plexapp.plugins.library
Oct 05, 2014 17:48:02 [0x1089f4000] DEBUG -  \* time => 0
Oct 05, 2014 17:48:02 [0x1089f4000] DEBUG -  \* state => playing
Oct 05, 2014 17:48:02 [0x1089f4000] WARN - Ignoring premature play progress for 0 ms on item 15273
Oct 05, 2014 17:48:02 [0x1089f4000] VERBOSE - Completed request: GET /:/progress?key=15273&identifier=com.plexapp.plugins.library&time=0&state=playing: 2200
Oct 05, 2014 17:48:02 [0x10bcca000] VERBOSE - Finished writing response for GET /:/progress?key=15273&identifier=com.plexapp.plugins.library&time=0&state=playing, 0 bytes in 51ms
Oct 05, 2014 17:48:02 [0x10bc47000] WARN - We didn't receive any data from 192.168.1.20:41100 in time, dropping connection.
Oct 05, 2014 17:48:02 [0x10bcca000] WARN - We didn't receive any data from 192.168.1.179:50765 in time, dropping connection.
Oct 05, 2014 17:48:03 [0x108eee000] VERBOSE - [IDLE] Removing (1->0) work item http_download - /photo/:/transcode?url=http%3A%2F%2Flocalhost%3A32400%2Flibrary%2Fmetadata%2F15273%2Fthumb%2F1408500461&width=300&height=440
Oct 05, 2014 17:48:03 [0x108eee000] VERBOSE - [IDLE] \* http_download - /photo/:/transcode?url=http%3A%2F%2Flocalhost%3A32400%2Flibrary%2Fmetadata%2F15273%2Fart%2F1408500461&width=1280&height=720 - 1 active item(s)
Oct 05, 2014 17:48:03 [0x108de8000] VERBOSE - [IDLE] Removing (1->0) work item http_download - /photo/:/transcode?url=http%3A%2F%2Flocalhost%3A32400%2Flibrary%2Fmetadata%2F15273%2Fart%2F1408500461&width=1280&height=720
Oct 05, 2014 17:48:03 [0x108de8000] VERBOSE - [IDLE] Server is now idle
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG - Request: [192.168.1.210:55212] GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655&X-Plex-Access-Key=BWSV622WQARJQHWA1KNQ&X-Plex-Access-Time=1412549280&X-Plex-Access-Code=iiA6%2BLrTjvbaTt2oI2NK%2FH4VBta2ZRGukxu9lZDOYT8%3D (25 live)
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG -  \* quality => 10
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG -  \* 3g => 0
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG -  \* url => http://192.168.1.38:32400/library/parts/15655
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG -  \* X-Plex-Access-Key => BWSV622WQARJQHWA1KNQ
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG -  \* X-Plex-Access-Time => 1412549280
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG -  \* X-Plex-Access-Code => iiA6+LrTjvbaTt2oI2NK/H4VBta2ZRGukxu9lZDOYT8=
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG - Cookie header in secure request: 
Oct 05, 2014 17:48:06 [0x10f140000] DEBUG - Checking cookie ''
Oct 05, 2014 17:48:06 [0x10f140000] ERROR - Client 'BWSV622WQARJQHWA1KNQ' access code is incorrect.
Oct 05, 2014 17:48:06 [0x10f140000] VERBOSE - Completed request: GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655: 401
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG - Request: [192.168.1.210:55218] GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655&X-Plex-Access-Key=BWSV622WQARJQHWA1KNQ&X-Plex-Access-Time=1412549280&X-Plex-Access-Code=iiA6%2BLrTjvbaTt2oI2NK%2FH4VBta2ZRGukxu9lZDOYT8%3D (26 live)
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG -  \* quality => 10
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG -  \* 3g => 0
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG -  \* url => http://192.168.1.38:32400/library/parts/15655
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG -  \* X-Plex-Access-Key => BWSV622WQARJQHWA1KNQ
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG -  \* X-Plex-Access-Time => 1412549280
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG -  \* X-Plex-Access-Code => iiA6+LrTjvbaTt2oI2NK/H4VBta2ZRGukxu9lZDOYT8=
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG - Cookie header in secure request: 
Oct 05, 2014 17:48:11 [0x108f7e000] DEBUG - Checking cookie ''
Oct 05, 2014 17:48:11 [0x108f7e000] ERROR - Client 'BWSV622WQARJQHWA1KNQ' access code is incorrect.
Oct 05, 2014 17:48:11 [0x108f7e000] VERBOSE - Completed request: GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655: 401
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG - Request: [192.168.1.210:55223] GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655&X-Plex-Access-Key=BWSV622WQARJQHWA1KNQ&X-Plex-Access-Time=1412549280&X-Plex-Access-Code=iiA6%2BLrTjvbaTt2oI2NK%2FH4VBta2ZRGukxu9lZDOYT8%3D (24 live)
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG -  \* quality => 10
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG -  \* 3g => 0
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG -  \* url => http://192.168.1.38:32400/library/parts/15655
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG -  \* X-Plex-Access-Key => BWSV622WQARJQHWA1KNQ
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG -  \* X-Plex-Access-Time => 1412549280
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG -  \* X-Plex-Access-Code => iiA6+LrTjvbaTt2oI2NK/H4VBta2ZRGukxu9lZDOYT8=
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG - Cookie header in secure request: 
Oct 05, 2014 17:48:16 [0x1089f4000] DEBUG - Checking cookie ''
Oct 05, 2014 17:48:16 [0x1089f4000] ERROR - Client 'BWSV622WQARJQHWA1KNQ' access code is incorrect.
Oct 05, 2014 17:48:16 [0x1089f4000] VERBOSE - Completed request: GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655: 401
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG - Setting capabilities: protocols=http-live-streaming,http-mp4-streaming;videoDecoders=h264(profile:high&resolution:1080&level:41};audioDecoders=mp3,aac,ac3(bitrate:300000&channels:6}
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG - Request: [192.168.1.210:55229] GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655&X-Plex-Access-Key=BWSV622WQARJQHWA1KNQ&X-Plex-Access-Time=1412549280&X-Plex-Access-Code=iiA6%2BLrTjvbaTt2oI2NK%2FH4VBta2ZRGukxu9lZDOYT8%3D (23 live)
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG -  \* quality => 10
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG -  \* 3g => 0
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG -  \* url => http://192.168.1.38:32400/library/parts/15655
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG -  \* X-Plex-Access-Key => BWSV622WQARJQHWA1KNQ
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG -  \* X-Plex-Access-Time => 1412549280
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG -  \* X-Plex-Access-Code => iiA6+LrTjvbaTt2oI2NK/H4VBta2ZRGukxu9lZDOYT8=
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG - Cookie header in secure request: 
Oct 05, 2014 17:48:21 [0x108f7e000] DEBUG - Checking cookie ''
Oct 05, 2014 17:48:21 [0x108f7e000] ERROR - Client 'BWSV622WQARJQHWA1KNQ' access code is incorrect.
Oct 05, 2014 17:48:21 [0x108f7e000] VERBOSE - Completed request: GET /video/:/transcode/segmented/start.m3u8?quality=10&3g=0&url=http%3A%2F%2F192.168.1.38%3A32400%2Flibrary%2Fparts%2F15655: 401

IF i turn on the HLS transcoding it works but i lost the multichannel Audio.

**Comment by ssalah75** [comment]
I have the same error that start recently.
I used to play all kind of movies before and never had an issue.
suddenly, some movies stopped working with error 2, and others works fine.
I can't tell exactly what changes took place before this issue came up.
but as I remember these activities took place recently, and I'm not sure if it has an effect:

- upgraded to the latest Plex Media server.
- installed pinnacle video editing software.
- used a different modem/router.

**Comment by jamvega** [comment]
I just had this problem using Playz on my LG TV as well.

I went to my PC, loaded up the plex server:
- Settings
- Show Advanced
- Player
- Uncheck DIRECT PLAY
 Then I tried playing the file again on my LG TV and it worked!  I guess this way the server converts the file first, then sends it to the TV, so that the TV doesn't have to do any conversions.

Hope this helps some of you.
