### ISSUE TITLE
Enhancement: consider making PlayZ Smart TV Alliance compatible

### ISSUE THREAD

**Issue by sander-git** [simonjhogan/PLAYz-Media-for-PLEX#75]
PlayZ is an HTML application that with limited modification (e.g. replace media object with HTML 5 video element) would work on a wider range of Smart TV Alliance compatible televisions (including LG, Panasonic, Toshiba and Philips). Perhaps consider adding compatibility for that to the application (check the <a href="https://developers.smarttv-alliance.org">Smart TV Alliance Developer website</a> for technical details).

**Comment by jwlee151** [comment]
Mr. Hogan, I have purchased PlayZ Media app from LG Smart World from my 55LA6900 Smart TV. 
I thank you very much for bringing it for LG Smart TV users. I've been using for more than a year. 
However, I recently purchased a PF1500 (LG projector with smart TV function). and Playz Media is not showing up on that machine's LG Smart World. 
As a customer who paid for an app from LG Smart World, I sent an inquiry to LG that why is Playz Media not showing up in LG Smart World form PF1500, and their answer is "the application provider has not yet developed a version designed for PF1500". I do not think you have to develop different version for each numerous models. 
If so, do you have plan to support PF1500?
