### ISSUE TITLE
Subtitle issue

### ISSUE THREAD

**Issue by Mindstorm96** [simonjhogan/PLAYz-Media-for-PLEX#8]
Hi, Great job !
Method for WebOs work fine and resolutions are ok on a 49UB850V (4K model).

- When clicking on option "subtitle:disabled"  appear a "Error 2" message on the upper right corner and subtitle are not disabled.
- Sometimes subtitles freeze on words, need to resume, stop and on menu launch again from last position to erase it.
- When i push "pause" the timer in the down bar stay on a xx:xx position not corresponding to reality but lenght of time bar is at the correct position (resume time position correct too)

cheers

Nico

**Comment by axebox** [comment]
I have this issue too, on the LG 65UB9500 with WebOS. 

Every video has subtitles and you can't turn them off.

**Comment by gennady-lebedev** [comment]
Same issue.
LG 42LB652 with WebOS

**Comment by rafaelgaspar** [comment]
+1 on LG42LB6500

**Comment by fkick** [comment]
simonjhogan can we assume development on this has ceased with the official client coming to the LG TVs?

**Comment by simonjhogan** [comment]
I am still tinkering ...

**Comment by frosstatx** [comment]
oficial app need a plex pass

**Comment by mrmarbury** [comment]
I have the same problem and it bothers me alot. Will this be fixed?

**Comment by simonjhogan** [comment]
there is nothing I can do about embedded subtitles ... the api for subtitles is literally on or off for external subtitles only ... so either use transcoding or re-encode you movies
